name: Update Rules
on: 
  schedule:
    - cron: '0 0,8,16 * * *'
  push:
   branches:
    - main

  workflow_dispatch:

  repository_dispatch:
   type:
    - [Manual-Update]

env:
  SCKEY: ${{ secrets.SCKEY }}
  PUSH_PUSH: ${{ secrets.PUSH_PUSH }}
  GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

  
jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update Rules
        run: |
          bash ./script/adblock/main.sh
          bash ./script/adguard/main.sh
          bash ./script/dns/main.sh
          bash ./script/allow/main.sh
          bash ./script/hosts/main.sh
          bash ./script/adblock+adguard/main.sh
          

      - name: Update other rules
        run: |
          cd rules
          rm *.txt
          wget -O ADgk.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -O kill-baidu-ad.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
          wget -O fasthosts.txt https://raw.githubusercontent.com/hacamer/filtering/master/hosts
      - name: Move files
        run: |
          cd script
          mv adblock.txt adguard.txt dns.txt hosts.txt allow.txt adblock+adguard.txt ../
          for i in $(ls ../*.txt); do
            sed -i '/^$/d' $i
          done
      - name: Update ReadMe
        run: |
          bash ./readme.sh

      - name: Git push assets to Github
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git push -u origin -f
      - name: Git push assets to Coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git remote add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/cats-team/adguard/AdRules.git"
          git push -u -f origin --all
      - name: Push Message
        run: |
          pip3 install requests
          python3 ./pusher.py
      - name: Manual-Update Other Repository
        run: |
          bash ./script/manual-update.sh
